version: '2'

services:

  node1:
    build: .
    environment:
      POSTGRES_USER: 'xtm'
      NODE_ID: 1
    ports:
      - "5432:5432"
    #depends_on:
    #  - node1
    #  - node2

  node2:
    build: .
    environment:
      POSTGRES_USER: 'xtm'
      NODE_ID: 2
    #ports:
    #  - "5432:15433"

  node3:
    build: .
    environment:
      POSTGRES_USER: 'xtm'
      NODE_ID: 3
    #ports:
    #  - "5432:15434"


